language: java
jdk: openjdk11
script:
  - mvn clean package
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - geracimov@gmail.com
    on_success: always
    on_failure: always